### ISSUE TITLE
stuck at circle after clicking on the Dropbox button (with journalctl output from fedora linux)

### ISSUE THREAD

**Issue by justtakingsomenotes** [trezor/trezor-password-manager#109]
Dear trezor-password-manager devs,

I observed this issue many times on different (linux) machines with different Trezor One devices, most of which have different firmwares (no firmware older than 18 months I believe). But this time I have a freshly installed fedora machine without tons of potentially interfering other stuff on it and I copied what it said in the journalctl output.

This problem does neither occur on Windows 10 nor on MacOS Big Sur, both of which I also use regularly.

My only workaround so far: Uninstall and reinstall Trezor password manager plugin for Chrome, re-register plugin with Dropbox (or Google Drive I guess) .

My user experience goes like this:
- while I have this issue with the password manager, the wallet works like a charm
- I also make sure that wallet.trezor.io does not conflict with my use of the password manager
- freshly installed fedora, happened on previous versions as well
- Chromium Version 91.0.4472.164 (Developer Build) Fedora Project (64-bit), happened on previous versions as well
-  Trezor bridge 2.0.27 RPM package installed, happened on previous versions as well
- udev rules version 2.1 RPM package installed, happened on previous versions as well
- flashed latest Trezor firmware yesterday (1.10.2), happened on previous versions as well
- I open the freshly installed trezor password manager plugin in chromium using Dropbox (and Google Drive until a few months ago)
- everything works fine
- **one reboot later**: trezor password manager is stuck after clicking on the Dropbox button, no numbers appear on my Trezor One, the circle keeps circling

`journalctl` output (which seems to be the same as the trezor logs that I forget how to access in the browser:
```
Sep 08 19:47:30 fedora systemd[1]: Started Hostname Service.
Sep 08 19:47:49 fedora trezord[1049]: POST /
Sep 08 19:47:49 fedora trezord[1049]: 127.0.0.1 - - [08/Sep/2021:19:47:49 +0200] "POST / HTTP/1.1" 200 21
Sep 08 19:47:49 fedora trezord[1049]: POST /enumerate
Sep 08 19:47:49 fedora trezord[1049]: 127.0.0.1 - - [08/Sep/2021:19:47:49 +0200] "POST /enumerate HTTP/1.1" 200 94
Sep 08 19:47:49 fedora trezord[1049]: POST /listen
Sep 08 19:47:50 fedora trezord[1049]: POST /acquire/1/null
Sep 08 19:47:50 fedora kernel: usb 7-2: reset full-speed USB device number 2 using uhci_hcd
Sep 08 19:47:50 fedora trezord[1049]: 127.0.0.1 - - [08/Sep/2021:19:47:50 +0200] "POST /acquire/1/null HTTP/1.1" 200 16
Sep 08 19:47:50 fedora trezord[1049]: POST /call/1
Sep 08 19:47:50 fedora trezord[1049]: 127.0.0.1 - - [08/Sep/2021:19:47:50 +0200] "POST /call/1 HTTP/1.1" 200 340
Sep 08 19:47:50 fedora trezord[1049]: 127.0.0.1 - - [08/Sep/2021:19:47:49 +0200] "POST /listen HTTP/1.1" 200 93
Sep 08 19:47:50 fedora trezord[1049]: POST /listen
Sep 08 19:47:50 fedora trezord[1049]: POST /release/1
Sep 08 19:47:50 fedora trezord[1049]: 127.0.0.1 - - [08/Sep/2021:19:47:50 +0200] "POST /release/1 HTTP/1.1" 200 16
Sep 08 19:47:51 fedora trezord[1049]: 127.0.0.1 - - [08/Sep/2021:19:47:50 +0200] "POST /listen HTTP/1.1" 200 94
Sep 08 19:47:51 fedora trezord[1049]: POST /listen
Sep 08 19:48:00 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed>
Sep 08 19:48:00 fedora systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Sep 08 19:48:00 fedora audit: BPF prog-id=57 op=UNLOAD
Sep 08 19:48:00 fedora audit: BPF prog-id=56 op=UNLOAD
Sep 08 19:48:42 fedora kernel: perf: interrupt took too long (3131 > 3126), lowering kernel.perf_event_max_sample_rate to 63000
```

I also captured everything related to USB with Wireshark in case this is useful for someone. Without having any knowledge about how USB works internally, I suspect that the `usb 7-2: reset full-speed USB device number 2 using uhci_hcd` is a problem?

Is there anything I can do myself apart from re-installing the plugin every time?

**Comment by tsusanka** [comment]
Would you know if this happened to you a week ago, let's say before Sep 3rd?

**Comment by justtakingsomenotes** [comment]
@tsusanka thanks for your reply. Yes, I can confirm that this happened many times during the last 6 months (at least), always on fedora.

When this issue started I wasn't aware that this may be fedora (or linux?) related. I use trezor password manager on many systems, usually Mac and Win10. When it happened before I always thought that this is a network issue on Dropbox's side. Now I believe that it's something USB related.

I'm sure I can reproduce it. And I have the Wireshark caption from yesterday. I'm happy to provide logs etc, I just need to know what kind of diagnostic stuff I need to do.

**Comment by justtakingsomenotes** [comment]
Update:

Same issue as described in intial post now with trezor firmware 1.10.0 on a Mac

**Comment by justtakingsomenotes** [comment]
Update: now same issue on mac OS 11.6:

- trezor bridge 2.0.27
- Chrome Version 93.0.4577.82 (Official Build) (x86_64)
- trezor firmware 1.10.0

**Comment by dallemon** [comment]
Just started having this issue on Windows 10 within the last week.
Has been working fine for a very long time and I use it almost daily.

**Comment by tsusanka** [comment]
We have reverted some of our changes. Please try again, did it help?

**Comment by dallemon** [comment]
> We have reverted some of our changes. Please try again, did it help?

Seems to be working again now.

**Comment by justtakingsomenotes** [comment]
> We have reverted some of our changes. Please try again, did it help?

The problem disappeared on MacOS, will check fedora and Win10 the coming days. Does the solution involve a firmware update or an update of the Chrome extension?

**Comment by dallemon** [comment]
> > We have reverted some of our changes. Please try again, did it help?
> 
> The problem disappeared on MacOS, will check fedora and Win10 the coming days. Does the solution involve a firmware update or an update of the Chrome extension?

I just updated the browser extension :)

**Comment by tsusanka** [comment]
Yes, we have released a fix few days back which should work with the new Dropbox setting. Let me know in case the issue would come back and thanks for the report.
