### ISSUE TITLE
If Bridge is turned off, Trezor One stays as Unreadable Device

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-password-manager#26]
How to reproduce: 
1. Open TPM, connect Trezor, login to TPM
2. Kill trezord process
3. The app will notice that Bridge is not installed, click Restart App 
![screenshot from 2018-08-02 18-19-58](https://user-images.githubusercontent.com/31442634/43596939-ee30fc10-9680-11e8-87e7-eeb11d8dc017.png)
4. The relaunched app tries to use WebUSB, however the connected device stays as Unreadable device, clicking on it / clicking on Check for devices does nothing. 
![screenshot from 2018-08-02 18-20-29](https://user-images.githubusercontent.com/31442634/43597039-31ad9c50-9681-11e8-8944-f2294491a004.png)

**Comment by stachrom** [comment]
Right now i am unable to use the TPM inside QUBES 4 - either with Trezor1 (T1) (Firmware 1.6.3 ) or Trezor Model T. 
The workaround for the Model T  mentioned here: https://github.com/trezor/trezor-core/issues/167#issuecomment-386796999 was not successfull. 
--> https://wiki.trezor.io/Qubes_OS

The wallet is still accessible with T1 in Qubes4 

On Debian and Windows 10 -  TPM ist working with both devices - i guess its all about the BRIDGE.

**Comment by chren-de-large** [comment]
Yes you are right, but model T should work on webUsb - in Windows, as well in Qubes.

**Comment by chren-de-large** [comment]
still an issue? even with new firmware?
