### ISSUE TITLE
Too long time to Add new entry

### ISSUE THREAD

**Issue by chren-de-large** [trezor/trezor-password-manager#41]
please, investigate why Add new entry takes so long to render empty entry. There could be possibly some glitch in code that is taking some time.

**Comment by keip** [comment]
There is a simple state variable newEntry which is set true to display an empty TableEntry component.
I see no glich in code, no callbacks just true/false state.
@chren-de-large is there a possibility that your computer was glitching? Because for me it works instantly.

**Comment by chren-de-large** [comment]
Yes, maybe we could consider to change it from React call to CSS transformation - like show/hide state ... will investigate whats the problem.

**Comment by chren-de-large** [comment]
will fix in updated react
