### ISSUE TITLE
Import: Autofill URL by Title when missing

### ISSUE THREAD

**Issue by slush0** [trezor/trezor-password-manager#45]
Currently, import of item with missing URL field silently fails. Application should fill it with Title instead of import failure.

**Comment by chren-de-large** [comment]
i dont like these solution:

`if (!!entry.title || !!entry.note)`

i would expect url will be filled by title or if missing title it will be fit by beutified URL - the same you can see when adding new entry - look

![oct-07-2018 15-42-46](https://user-images.githubusercontent.com/1671375/46582475-b603ef00-ca47-11e8-9577-00aa05136f39.gif)
