### ISSUE TITLE
Add "Copy to clipboard" button

### ISSUE THREAD

**Issue by slush0** [trezor/trezor-password-manager#46]
Sometimes autofill ("Login" button) does not work, for various reasons. For example, I do use Chrome only for password manager, and I want to log into sites loaded in Firefox.

Please add button "Copy password to clipboard" next to "Login" button, so users can save many clicks (Edit -> Show password -> Select all -> Ctrl+C).

**Comment by chren-de-large** [comment]
actually there is copy to clipboard btn .... when you hover on Entry you can see "stars" and when you hover them you can copy2clipboard password.

So this is more UID issue
