### ISSUE TITLE
Export stops working if there is an entry being edited

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-password-manager#50]
How to reproduce: 
1. Start editing an entry
2. Do not save it
3. Click Export storage
4. Save the entry now
5. Click Export storage again
6. Export stops working. Also, it is impossible to actually save that entry - Save/ Discard buttons keep being there

![screenshot from 2018-10-15 15-00-45](https://user-images.githubusercontent.com/31442634/46952538-6cd91e00-d08b-11e8-8a73-95b0ee572705.png)

**Comment by pankrats** [comment]
Updated the steps to reproduce the issue!

**Comment by pankrats** [comment]
![screenshot from 2018-10-16 12-14-58](https://user-images.githubusercontent.com/31442634/47009609-38be3580-d13d-11e8-887e-cbe84ff074ee.png)

**Comment by keip** [comment]
this issue was caused by blob type in exported data

**Comment by pankrats** [comment]
Looks like it is fixed in version 0.6.3.4
