### ISSUE TITLE
1000+ characters breaks saving of item

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-password-manager#52]
You enter more than 1000 characters to secret note and dismiss edit.
You start to edit different item.
after you come back you are not able to save it even there is less than 1000 characters in secret note

![screenshot from 2018-10-17 13-33-59](https://user-images.githubusercontent.com/31506317/47084091-d9caf000-d212-11e8-84a6-7f60798284f0.png)

**Comment by pankrats** [comment]
![screenshot from 2018-10-17 14-10-20](https://user-images.githubusercontent.com/31442634/47085313-91adcc80-d216-11e8-8d95-116bddd858b0.png)
