### ISSUE TITLE
Waking up ...

### ISSUE THREAD

**Issue by pavoltravnik** [trezor/trezor-password-manager#53]
My Trezor password manager is broken and still in mode Waking up... Tried to reinstall app and restart computer, nothing helped. Wallet works fine.
 ![screen shot 2018-10-22 at 14 25 38](https://user-images.githubusercontent.com/21983609/47292154-6f48f400-d606-11e8-9f35-ab5e6c597d55.png)

**Comment by keip** [comment]
Hi, do you have some errors in the console?

If you right click on the extension then click Manage Extensions, there is an Inspect views sectio in whitch there is 2 pages index.html and background page, send the screenshots from theese 2.
Also i need to know whitch model of trezor do you use?

Thank you!

**Comment by pavoltravnik** [comment]
Trezor needs to be updated to the latest version 1.6.3. I had 1.5.x and after update it went to 1.6.0, so you have to update it probably twice in a row.
