### ISSUE TITLE
Trezor Passwor Manager - Tags not working properly after 28th tag is added. 

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-password-manager#57]
@keip, pls, have a look. 

https://github.com/satoshilabs/trezor-qa/issues/59

**Comment by chren-de-large** [comment]
resolved, test please

**Comment by pankrats** [comment]
brilliant! closing

**Comment by johnsonsan** [comment]
I would like to apologize, im doing more research. Thanks team

**Comment by johnsonsan** [comment]
If you would like to send suggestions please feel free.
