### ISSUE TITLE
Errors in extension

### ISSUE THREAD

**Issue by keip** [trezor/trezor-password-manager#59]
Go to PM, click on "edit" entry (don't confirm/cancel on trezor) and switch user. The error will appear, and it's caused by unmounted component trying to setState()...

<img width="493" alt="tinygrab screen shot 09-01-2019 15 34 47" src="https://user-images.githubusercontent.com/1011630/50905915-36116a80-1424-11e9-8c0e-3724346f62dc.png">

<img width="837" alt="tinygrab screen shot 09-01-2019 15 39 13" src="https://user-images.githubusercontent.com/1011630/50906148-c51e8280-1424-11e9-8970-90257863e828.png">

**Comment by chren-de-large** [comment]
review please

**Comment by keip** [comment]
good job!
