### ISSUE TITLE
Left Navigation (Side Panel) - the Icon is not on the same Line as the Tag

### ISSUE THREAD

**Issue by stachrom** [trezor/trezor-password-manager#60]
I would expect the icons in the left sidepanel  on the same line as the  tag. 
Currently they are diplayed on two lines. 

https://github.com/trezor/trezor-password-manager/blob/d87d00197690686447fc01e54bd640b5d0495824/source/app/dashboard/side_panel/_side_panel.scss#L142

current CSS:  
.navigation ul > li > a span {
    display: inline-block;
... 

this would fix the issue alt least for me: 
 
.navigation ul > li > a span {
    display: inline;
....

**Comment by pankrats** [comment]
Can confirm. 
![screenshot from 2019-01-23 12-40-47](https://user-images.githubusercontent.com/31442634/51604138-23129600-1f0c-11e9-8b92-55efa96ac7ef.png)

**Comment by chren-de-large** [comment]
thanks @stachrom ! 

will be soon (in 24h) released in hotfix 0.6.3.6
