### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by ajbt200128** [trezor/trezor-password-manager#64]
Love the password manager, but some sort of road map would be super appreciated.

**Comment by RayMetz100** [comment]
+1
Please enable Brave Browser integration.
https://github.com/brave/brave-browser/issues/3120

**Comment by prusnak** [comment]
@ajbt200128 roadmap are open tickets - everyone is free to contribute the code to close them

@RayMetz100 this is broken in the brave browser, nothing to do from our side
