### ISSUE TITLE
Trezor Chrome extension prevents pasting without formatting (CMD+Shift+V)

### ISSUE THREAD

**Issue by ramuta** [trezor/trezor-password-manager#69]
I often use a Mac keyboard combo CMD+Shift+V for pasting text without formatting included, but recently I noticed that the combo stopped working. Upon further inspection, I figured out it might have something to do with the Trezor Password Manager Chrome extension. If I turn it off, the CMD+Shift+V combo magically starts working again.

Does a new Trezor extension happen to use this keyboard combo for some purposes?

This commit looks suspicious... https://github.com/trezor/trezor-password-manager/commit/2c7c11d3b7c38820aebd8e5568b8d26bd86eb154

**Comment by prusnak** [comment]
Yes, this commit was a mistake.

@1000101 Would "Ctrl+Shift+F" be acceptable for filling the form on Linux?
@ramuta Would "Cmd+Shift+F" be acceptable for filling the form on macOS?

**Comment by ramuta** [comment]
@prusnak 

cmd+shift+f is reserved for "Always show toolbar in full screen" in Chrome (under the View menu).

The ones that seem available are:

- cmd+shift+k
- cmd+shift+p
- cmd+shift+o
- cmd+shift+u
- cmd+shift+y
- cmd+shift+e

**Comment by ramuta** [comment]
@prusnak 
Should I make a PR, or will any of you fix it?

**Comment by prusnak** [comment]
The only combination that is available on Linux is Ctrl+Shift+U

**Comment by prusnak** [comment]
The only combination from the above list usable on Linux is Ctrl+Shift+U.

Do we want Cmd+Shift+U on MacOS?

**Comment by ramuta** [comment]
@prusnak yes, CMD+Shift+U would be a good choice :)

**Comment by ramuta** [comment]
Here's the PR: https://github.com/trezor/trezor-password-manager/pull/70
