### ISSUE TITLE
Ctrl+Shift+U combination

### ISSUE THREAD

**Issue by 1000101** [trezor/trezor-password-manager#72]
> Here's the PR: https://github.com/trezor/trezor-password-manager/pull/70
> 
> _Originally posted by @ramuta in https://github.com/trezor/trezor-password-manager/issues/69#issuecomment-482127302_

I think that this PR forgot to change the combination for App restart, which is now used twice for both fill in form & app restart

**Comment by ramuta** [comment]
Oh, snap... Do you have any suggestion for another key combo for Fill Login Form?

**Comment by ramuta** [comment]
Perhaps CTRL+Shift+Y - this one seems to be still available.

**Comment by 1000101** [comment]
> Perhaps CTRL+Shift+Y - this one seems to be still available.

Seems to be used by Firefox to open Library. Don't know how many people use it though.

**Comment by ramuta** [comment]
> > Perhaps CTRL+Shift+Y - this one seems to be still available.
> 
> Seems to be used by Firefox to open Library. Don't know how many people use it though.

Hm, I can't seem to find any reference on that online (I checked on [this website](https://defkey.com/what-means/ctrl-shift-y))... I also tried this combo in Firefox on Mac and it doesn't seem to do anything.

Anyway, another option is CTRL+Shift+E. What do you think about this one?

**Comment by prusnak** [comment]
We already changed that to Ctrl+Shift+U: 
https://github.com/trezor/trezor-password-manager/commit/99489bf7cff0a9236b417468c3b2b0fdfea6b0b5

> Hm, I can't seem to find any reference on that online

It opens the library on Linux.

**Comment by ramuta** [comment]
Hey @prusnak - the problem is that we missed that Ctrl+Shift+U is already used in the Trezor Password Manager manifest.json (see lines 17 and 23 [here](https://github.com/trezor/trezor-password-manager/blob/master/extension/manifest.json)). So I think this issue should be re-opened.

**Comment by prusnak** [comment]
I just removed restart app action: https://github.com/trezor/trezor-password-manager/commit/9f673d2af3bd21850c8476afa5f2e6fa1c92f86c
