### ISSUE TITLE
Firefox and other community

### ISSUE THREAD

**Issue by raisty** [trezor/trezor-password-manager#73]
Will be interesting to develop this software for firefox community / separate application.
Thanks.

**Comment by prusnak** [comment]
Only Chrome is supported at the moment.

**Comment by SKUndef** [comment]
What about this: https://www.reddit.com/r/TREZOR/comments/9h4unt/trezor_password_manager_for_firefox/. 2 years and the standalone solution is not out yet!

Please progress with support for other platforms.

Thanks,
Regards
