### ISSUE TITLE
Bug on Brave browser

### ISSUE THREAD

**Issue by raisty** [trezor/trezor-password-manager#74]
On Brave browser is application hanging, when you click on Google drive.
Preloader turning and nothing happen.

Steps:
* Install the application on Brave browser
* Click on an extension to enable application
* Connect Trezor One
* Click on Google Drive

The version of brave:
`0.61.52 Chromium: 73.0.3683.86`

**Comment by prusnak** [comment]
Brave is not supported.

**Comment by prusnak** [comment]
This is a bug in Brave browser. Report it to their bugtracker if you want to have this fixed.

**Comment by raisty** [comment]
Same issue with Google Chrome
Version 74.0.3729.169
