### ISSUE TITLE
ChromeOS Support?

### ISSUE THREAD

**Issue by MAHDTech** [trezor/trezor-password-manager#75]
Hi,

Is there any WebUSB support in the Trezor Password Manager?

I am unable to get the password manager working on ChromeOS, the device appears, shows connected in Chrome, but the Password Manager doesn't activate/load.

Cheers.

Trezor Model T Firmware v2.0.1.0
ChromeOS v74.0.3729.125

**Comment by keip** [comment]
Hi, unfortunately ChromeOS is not supported in the Trezor Password Manager and Trezor Bridge is not compatible with ChromeOS.
