### ISSUE TITLE
Autofill fails on Vanguard

### ISSUE THREAD

**Issue by davidrapoport** [trezor/trezor-password-manager#91]
When I try to autofill my passwords onto investor.vanguard.com it fills in the username and password as expected. Then when I try to submit the form I see two error messages on the page that say "Please fill out this field."
I've checked the source of the website and I see that my username/password are in the value attribute of the input. But they input is also marked as ng-invalid and ng-pristine. Both of which are removed once I copy and paste my username/password combo into the fields. Is there anyway to fix this or would this better be done on Vanguard's side?

**Comment by prusnak** [comment]
Vanguard side

**Comment by davidrapoport** [comment]
I disagree, I just tried doing the same action with LastPass and it works without any problems.
