### ISSUE TITLE
TPM is not working with latest FW 2.3.2 with auto-lock feature enabled

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-password-manager#95]
FW: Latest firmware 2.3.2 revison 6ebb388 includes auto-lock feature. 
Browser:Chromium | 83.0.4103.106 (Developer Build) (64-bit)
TPM 0.7.0

TPM is not expecting model T to be autolocked. 
It's says saving but new entry is not saved even you unlock device after some time.

![image](https://user-images.githubusercontent.com/31506317/85986816-15105100-b9ed-11ea-9af1-430e3e69c8d2.png)

When you pres discard saving icon/animation  is still there
When you reload TPM there is no entry saved.

**Comment by bosomt** [comment]
same problem when trying to connect to TT that's already autolocked 
see video: https://www.youtube.com/watch?v=V73-tYJQRmQ&feature=youtu.be
device's diplay just blinks but no unlock via PIN dialogue.

Trezor model T commit revision ca3dd2b
Chromium | 83.0.4103.106
TPM 0.7.0

**Comment by sorooris** [comment]
confirming in 14a8da9

**Comment by tsusanka** [comment]
This should be fixed hopefully by https://github.com/trezor/connect/pull/619, deploying Connect and bumping TPM. I am coordinating with others and let you know when that happens for a retest.

**Comment by tsusanka** [comment]
@bosomt @sorooris could you please retest? The same firmware revision is just fine, or use current master.

**Comment by sorooris** [comment]
**QA OK**
model T **2.3.2**, revision **b8127c5**
browser: Chromium **83.0.4103.116**
TPM **0.7.0**
Tested the registration and sign-in flows with autolock t=10s.

**Comment by tsusanka** [comment]
Great :tada:
